name: 'Count lines of code (CLOC)'
description: 'Count lines of code using https://github.com/AlDanial/cloc'

inputs:
  path:
    description: 'Files or folders to analyze'
    required: false
    default: null
  # Input Options

  # Processing Options
  by_file:
    description: 'Report results for every source file encountered.'
    required: false
    default: false
  by_file_by_lang:
    description: 'Report results for every source file encountered in addition to reporting by language.'
    required: false
    default: true
  # Filter options
  exclude_list_file:
    description: 'Ignore files and/or directories whose names appear in FILE.  FILE should have one file name per line. Only exact matches are ignored; relative path names will be resolved starting from the directory where cloc is invoked. See also --list-file.'
    required: false
    default: false
  # Debug Options

  # Output Options
  report_file:
    description: 'Write the results to FILE instead of standard output.'
    required: false
    default: 'cloc.txt'

runs:
  using: 'docker'
  image: 'Dockerfile'
