name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run CLOC
      uses: AgenttiX/cloc-action@master
    - name: Upload CLOC output as a build artifact
      uses: actions/upload-artifact@v2
      with:
        name: cloc
        path: cloc.txt
